### ISSUE TITLE
Issue running the Evaluation function

### ISSUE THREAD

**Issue by Zorgrox** [emef/sdc#1]
python chauffeur.py bagdir/HMB_2.bag modelweights/cnn.json modelweights/cnn.weights modelweights/lstm.json modelweights/lstm.weights

Is this the way that the evaluation driver should be run? While not included in this directory, I figured that since it was likely you programmed that as well, this would be a better place to ask. When I run it, I get the error that there are incompatible input dimensions. 
ValueError: Shapes (4, ?, 30, 40, 20) and () are incompatible
The error seems to be coming from loading the cnn.json, 
any ideas?
Thanks!

**Comment by emef** [comment]
Hey! Thanks for checking out the repo. To be completely honest with you, I really don't remember :) The udacity folks were the ones that ran that particular evaluation script and hosted the weights I gave them.

**Comment by Zorgrox** [comment]
It seems to be a problem with actually loading the cnn.json that was given, do you still have a copy of the original? 
Running model = model_from_json(open(json_path, 'r').read()), is what gives the error, so it fails to load the JSON file.
As far as I can tell, I think it might have something to do with a null value? the "?" can be changed to a value, by editing the input dimension in the json, but I can't figure out what to do for the latter portion.
Thanks again!

**Comment by emef** [comment]
The most likely explanation for this would be a version mismatch of tensorflow/keras. Maybe you can try downgrading your packages and trying again? I don't have the originals, but I can't see a reason the ones provided wouldn't be identical. I don't believe I gave udacity more than one version of them.

**Comment by Zorgrox** [comment]
Do you know what version of Tensorflow was used for this? I know that the Keras version used was 1.1.1, which I have installed, but I'm not sure as where to find the proper version of Tensor Flow

**Comment by emef** [comment]
This was back in october 2016, which looks like maybe 0.10 or 0.11.

**Comment by Zorgrox** [comment]
0.12 appears to have worked, thank you
